@startuml

note "代理模式类图" as N1
interface Subject {
    request()
}
class RealSubject {
     request()
}
class Proxy {
    request()
}

Subject <|... RealSubject
Subject <|... Proxy

RealSubject <--left Proxy
@enduml